"Julia nightly, OS X":
  tags:
    - osx
  script:
    - curl -s -o setup-julia https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/setup-julia && source setup-julia nightly
    - julia -e 'symlink(ENV["CI_PROJECT_DIR"], Pkg.dir(ENV["PKG_NAME"])); Pkg.resolve(); Pkg.build(ENV["PKG_NAME"]); Pkg.test(ENV["PKG_NAME"])'


"Julia nightly, Linux (amd64)":
  tags:
    - linux
    - amd64
  script:
    - curl -s -o setup-julia https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/setup-julia && source setup-julia nightly
    - julia -e 'symlink(ENV["CI_PROJECT_DIR"], Pkg.dir(ENV["PKG_NAME"])); Pkg.resolve(); Pkg.build(ENV["PKG_NAME"]); Pkg.test(ENV["PKG_NAME"]; coverage=true)'
    - julia -e 'cd(Pkg.dir(ENV["PKG_NAME"])); Pkg.add("Coverage"); using Coverage; Codecov.submit_local(process_folder())'


"Julia nightly, Linux (i386)":
  tags:
    - linux
    - i386
  script:
    - curl -s -o setup-julia https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/setup-julia && source setup-julia nightly
    - julia -e 'symlink(ENV["CI_PROJECT_DIR"], Pkg.dir(ENV["PKG_NAME"])); Pkg.resolve(); Pkg.build(ENV["PKG_NAME"]); Pkg.test(ENV["PKG_NAME"])'
